[package]
name = "windows-tree-output-viewer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eframe = "0.23.0"
thiserror = "1.0.49"
anyhow = "1.0.75"